package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.event.ActionEvent;

import javafx.scene.layout.AnchorPane;

public class Controller {
	@FXML
	private Button btnIniciarServer;
	@FXML
	private AnchorPane apMissatges;

	// Event Listener on Button[#btnIniciarServer].onAction
	@FXML
	public void handleBtnIniciarServer(ActionEvent event) {
		// TODO Autogenerated
		//metodes.CensuraParaules.carregarInsults();
		servidorChat.ServidorChat.iniciarServidor();
	}
}
